#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Prettier 포맷팅 체크
pnpm exec prettier --check "**/*.{ts,tsx,js,jsx,json,css,md}" --ignore-path .prettierignore || exit 1

# ESLint 체크
pnpm lint || exit 1

